/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#ffb4aa',
        'primary-container': '#e50914',
        'on-primary': '#690003',
        'on-primary-container': '#fff7f6',
        'primary-fixed': '#ffdad5',
        'primary-fixed-dim': '#ffb4aa',
        'inverse-primary': '#c0000c',
        secondary: '#53e076',
        'secondary-container': '#02b04c',
        'on-secondary': '#003914',
        'on-secondary-container': '#003a14',
        'secondary-fixed': '#72fe8f',
        'secondary-fixed-dim': '#53e076',
        background: '#131313',
        'on-background': '#e5e2e1',
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-surface': '#e5e2e1',
        'surface-variant': '#353534',
        'on-surface-variant': '#e9bcb6',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        outline: '#af8782',
        'outline-variant': '#5e3f3b',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        tertiary: '#c6c6c7',
        'tertiary-container': '#717373',
        'on-tertiary': '#2f3131',
        'on-tertiary-container': '#f9f9f9',
        'tertiary-fixed': '#e2e2e2',
        'tertiary-fixed-dim': '#c6c6c7',
        'surface-tint': '#ffb4aa',
        'app-background': 'var(--app-background)',
        'app-primary-text': 'var(--app-primary-text)',
        'app-muted-text': 'var(--app-muted-text)',
        'app-accent': 'var(--app-accent)',
        'app-divider': 'var(--app-divider)',
        // Pricing reference tokens (scoped pricing-* to avoid global bleed)
        'pricing-bg': '#111111',
        'pricing-card': '#202020',
        'pricing-card-hover': '#272727',
        'pricing-border': '#363636',
        'pricing-red': '#ff0718',
        'pricing-red-light': '#ff3342',
        'pricing-red-dark': '#c9000e',
        'pricing-white': '#ffffff',
        'pricing-text': '#eeeeee',
        'pricing-muted': '#999999',
        'pricing-green': '#23d96b',
      },
      fontFamily: {
        'display-lg': ['Inter', 'system-ui', 'sans-serif'],
        'headline-lg': ['Inter', 'system-ui', 'sans-serif'],
        'headline-md': ['Inter', 'system-ui', 'sans-serif'],
        'headline-sm': ['Inter', 'system-ui', 'sans-serif'],
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'label-lg': ['JetBrains Mono', 'monospace'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'label-sm': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '72px', letterSpacing: '-0.04em', fontWeight: '800' }],
        'display-md': ['48px', { lineHeight: '56px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['16px', { lineHeight: '24px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        'gutter': '24px',
        'container-max': '1440px',
        'base': '8px',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      boxShadow: {
        pricing: '0 20px 45px rgba(0,0,0,0.45), 0 0 25px rgba(255,7,24,0.08)',
        'pricing-popular': '0 0 30px rgba(255,7,24,0.08)',
        'pricing-popular-hover': '0 25px 55px rgba(0,0,0,0.5), 0 0 35px rgba(255,7,24,0.14)',
      },
      backgroundImage: {
        'pricing-card': 'linear-gradient(145deg, #252525, #1c1c1c)',
        'pricing-card-popular': 'linear-gradient(145deg, #2a2a2a, #202020)',
        'pricing-body': 'radial-gradient(circle at 50% 0%, rgba(255,7,24,0.10), transparent 35%)',
      },
    },
  },
  plugins: [],
}
